---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-installer
  namespace: trident
spec:
  replicas: 1
  selector:
    matchLabels:
      name: trident-installer
  template:
    metadata:
      labels:
        name: trident-installer
    spec:
      serviceAccountName: trident-installer
      containers:
        - name: trident-installer
          image: netapp/ez-rancher-trident-installer:0.0.1
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "trident-installer"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
